[component]
structures = [ "content_blocks" ]
label = "Contact Form"
description = "Generic contact form"
icon = "wysiwyg"
tags = ["Text"]

[props]
form_title = "écris moi"
form_description = "N'hésite pas à me contacter pour plus d'infos"
form_success_page = "/"
form_submission_email = "leane.roz@gmail.com" # Add your email for contact form
form_button_text = "Envoyer"
