[component]
structures = [ "content_blocks" ]
label = "Newsletter Form"
description = "Generic newsletter form"
icon = "wysiwyg"
tags = ["Text"]

[props]

newsletter_title = "Reste informé"
newsletter_description = "En t'inscrivant à ma Newsletter tu seras informé sur mes dernières créations et mes articles"
newsletter_identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3"
newsletter_button = "Souscription"
